### ISSUE TITLE
Create Games Table

### ISSUE THREAD

**Issue by batshoes** [batshoes/hopscotch#1]
Generate the resource for the Games Table
add 
Games
  -Title
  -Description
  -Rules/Drink — I don’t know if “how much to drink per rule” should be a separate column in the table or if we should just attribute the picture with the drop down box...
  -Category/Attribution — “Movie” “TV” “Card” “Sport” “Other"
  -Likes/Rating

**Comment by glarson284** [comment]
Created Games and Rules Table
